#!/usr/bin/env python
"""Programmatically initialize topic workspace folders and default templates.
"""

import os
import shutil
import sys
import argparse
from datetime import date, datetime
from pathlib import Path

def keep_a_copy(p: Path) -> Path:
    """Put the current contents of *p* somewhere recoverable, and say where.

    `.backup` is the convention the rest of the workspace already uses — every
    scanner skips a path with it as a component, and `magi wiki
    refactor-concept` and `magi link` both write there. A second-granularity
    stamp is not a unique name, so take the first free one rather than
    overwriting the copy an earlier call in this same run just made.
    """
    stamp = datetime.now().strftime("%Y-%m-%d_%H%M%S")
    backup_dir = p.parent / ".backup"
    backup_dir.mkdir(parents=True, exist_ok=True)
    dest = backup_dir / f"{p.stem}_{stamp}{p.suffix}"
    n = 2
    while dest.exists():
        dest = backup_dir / f"{p.stem}_{stamp}-{n}{p.suffix}"
        n += 1
    shutil.copy2(p, dest)
    return dest

def safe_write(p: Path, content: str, force: bool):
    if p.exists():
        if not force:
            print(f"Skipping existing {p}")
            return
        # --force is the only way to reach this line, and what it lands on is
        # ORIGINAL: config.md is the scope a person wrote, log.md is the
        # running record, config.yaml is their settings. "Overwrite existing
        # config/log/index files" is an honest description of the flag and
        # still leaves no way back from a mistyped one.
        kept = keep_a_copy(p)
        print(f"Overwriting {p} (previous contents kept at {kept})")
    p.write_text(content, encoding="utf-8")

def create_minimal_index(path: Path, title: str, today: str, force: bool = False):
    """Scaffold one directory's `_index.md` using the shared renderer.

    The hand-rolled version here claimed "Generated by local magi lint",
    which was never true of this command, and emitted a `## Recent Changes`
    section with one bootstrap line that nothing ever added to. Between them,
    `magi init`, `magi lint --fix` and `magi wiki reindex` wrote three
    different formats into the same file.
    """
    from magi.core.wiki_common import render_index

    safe_write(path, render_index(path.parent, today=today), force)

def main(argv=None):
    parser = argparse.ArgumentParser(prog="magi init", description="Initialize topic workspace")
    parser.add_argument("--topic-dir", default=".", help="Topic directory path (default: current directory)")
    parser.add_argument("--name", default="My Topic", help="Topic name/title")
    parser.add_argument("--scope", default="A topic wiki.", help="Topic scope description")
    parser.add_argument("--force", action="store_true", help="Overwrite existing config/log/index files")
    args = parser.parse_args(argv)

    topic_path = Path(args.topic_dir).resolve()
    today = date.today().isoformat()

    # 1. Folders to create
    subdirs = [
        "raw",
        "raw/articles",
        "raw/papers",
        "raw/repos",
        "raw/notes",
        "raw/data",
        "wiki",
        "wiki/concepts",
        "wiki/topics",
        "wiki/references",
        "wiki/theses",
        "output",
        "inbox",
        "inbox/.processed",
        "scratch"
    ]

    for d in subdirs:
        p = topic_path / d
        p.mkdir(parents=True, exist_ok=True)

    # 2. config.md
    config_content = f"""---
title: "{args.name}"
scope: "{args.scope}"
created: {today}
---

# {args.name}

## Scope

{args.scope}

## Conventions

- Source files go in `raw/` under the appropriate subdirectory
- Compiled articles go in `wiki/references/` (papers) and `wiki/concepts/` (terms)
- All compiled pages use YAML frontmatter and `[[double-bracket]]` concept links
"""
    safe_write(topic_path / "config.md", config_content, args.force)

    # 3. log.md
    log_content = f"""# Log

## [{today}] init | Created new topic wiki
"""
    safe_write(topic_path / "log.md", log_content, args.force)

    # 4. Root _index.md
    root_index_content = f"""# {args.name}

> Topic wiki initialized on {today}.

## Quick Navigation

| Directory | Purpose |
|-----------|---------|
| [raw/](raw/) | Raw source materials |
| [wiki/](wiki/) | Compiled knowledge base |
| [output/](output/) | Generated artifacts — except `output/ingest/` and `output/radar/`, which record decisions you made and cannot be rebuilt |
| [inbox/](inbox/) | Pending ingestion |

## Statistics

- Raw sources: 0
- Compiled articles: 0
- Concepts: 0
"""
    safe_write(topic_path / "_index.md", root_index_content, args.force)

    # 5. Minimal _index.md files for subdirectories
    dir_titles = [
        ("raw", "Raw"),
        ("raw/articles", "Articles"),
        ("raw/papers", "Papers"),
        ("raw/repos", "Repos"),
        ("raw/notes", "Notes"),
        ("raw/data", "Data"),
        ("wiki", "Wiki"),
        ("wiki/concepts", "Concepts"),
        ("wiki/topics", "Topics"),
        ("wiki/references", "References"),
        ("wiki/theses", "Theses"),
        ("output", "Output"),
    ]

    for rel_path, title in dir_titles:
        p = topic_path / rel_path / "_index.md"
        create_minimal_index(p, title, today, args.force)

    # 6. Agent entry protocol: CLAUDE.md (Claude Code) + AGENTS.md (Codex
    # et al.) share one body so every host gets the same onboarding.
    protocol = f"""# MAGI Research Workspace: {args.name}

This directory is a MAGI topic workspace — an agent-native research
environment. Scope: {args.scope}

## On entering (do this first)

1. `magi sync` — sync ratio, three-core status, and concrete restore hints.
   Add `--fix` to run the deterministic ones (graph build, index, backlog
   sync, task store) instead of typing them out; it reports what still
   needs a person. `--dry-run` shows the plan first.
2. `bd prime` — inject current work state (ready/blocked/in-progress tasks).

## The three cores

- **Knowledge** (`wiki/`): concept cards, reference cards, theses.
  Produced by the ingest/compile skills; queried via `magi graph query`,
  `magi wiki context`, `magi grep`.
- **Work state** (beads): `bd ready` lists actionable tasks. Track research
  work with typed issues: question / survey / derivation / computation /
  experiment / review (`bd create -t <type> "..."`). These six research types
  are CUSTOM types configured by `magi pm init`; the generic type list from
  `bd prime` (task/bug/feature) does not supersede them.
- **Retrieval**: `magi search "..."` (hybrid BM25+vector; build/refresh with
  `magi index`); `magi grep` for exact regex. After a search, always read the
  underlying file before citing it.

## Shortcuts worth preferring

- `magi sync --fix` instead of running graph/index/backlog commands by hand.
- `magi ingest auto <path>` (or bare, for all of `inbox/`) instead of choosing
  between ingest mineru/ocr/tex/add and remembering `ingest finalize`.
- `magi each <command>` to run one command across every topic of a hub.
- `magi math check --json` after a batch of ingests, instead of checking each
  file. Ingestion's signature failure is a `$$` that lost its closing pair and
  swallowed the paragraph after it — that parses as valid LaTeX, so nothing
  else catches it. Work the list with the `wiki_math_fix` skill.

## Asking, and who does it

Only the agent talking to the human asks the human. If you are a sub-agent, the
question will not reach them on most hosts and hangs on some — put it in the
report you return instead, on its own line:

    NEEDS-DECISION: <the question> | options: <a> / <b> | default if unanswered: <x>

Whoever spawned you collects these and asks once, together. Ten sub-agents must
not become ten interruptions.

If you are the main agent and nobody is there (a scheduled run, a piped run, CI),
do not guess and do not wait: stop and state what you would have asked.

Ask before anything expensive or irreversible, and say what it costs in the same
breath — "this is 34 pages, so roughly 34 sub-agent calls" is a question someone
can answer; "proceed?" is not.

## Ground rules

- Durable state lives in files and databases here — not in your context.
  Record work in bd issues; record knowledge as wiki cards.
- Do NOT answer research questions from parametric memory. Retrieve from
  `wiki/` and cite `[[wikilinks]]`; verify claims with `magi verify`.
- Syntax for any command: `magi <command> --help`. Overview: `magi --help`.
- Stuck, or asked how something works? The manual ships with the CLI —
  `magi guide --search "<the error>"` finds the section, `magi guide
  --symptoms` is the symptom→fix index, `magi guide <chapter>` reads one.
  Prefer it over recalling flags from memory; add `--json` for parsing.
- The wiki_* skills teach when/why to run each pipeline (ingest, compile,
  enrich, link, lint, ask, audit, research).
"""
    safe_write(topic_path / "CLAUDE.md", protocol, args.force)
    safe_write(topic_path / "AGENTS.md", protocol, args.force)

    # 7. Starter config.yaml (workspace-level; wins over ~/.config/magi/)
    config_yaml = """# MAGI workspace configuration (discovered by upward walk from cwd)
ollama:
  base_url: "http://127.0.0.1:11434"
  autostart: true      # start a stopped local Ollama on demand
  embed_batch: 16      # chunks per embedding request; raise on a roomy machine
models:
  ocr: "glm-ocr:q8_0"
  embedding: "qwen3-embedding:0.6b"
ocr:
  # Deliberately absent, not empty. Settings layer: this file overrides
  # ~/.config/magi/config.yaml key by key, and an explicit "" is a value —
  # it would shadow a token set once for you and leave every new workspace
  # unable to reach MinerU for no visible reason. Put the token in the user
  # file; uncomment here only to give this one topic a different key.
  # mineru_api_token: ""
  use_mineru: false
  timeout: 180
  dpi: 150
semantic_link:
  threshold: 0.75
  merge_threshold: 0.85
  auto_merge_threshold: 0.95

# Literature radar (magi radar harvest)
radar:
  # A Semantic Scholar key is free and optional; without one the radar
  # shares an anonymous quota with everybody. $SEMANTIC_SCHOLAR_API_KEY
  # wins over this file. Deliberately absent rather than empty — see the
  # note on ocr.mineru_api_token above for why.
  # s2_api_key: ""
  arxiv_categories:
    - cond-mat.str-el
    - hep-th
  # Papers that describe what you care about — often other people's. May stay
  # empty: every arXiv ID on a reference card is merged in automatically.
  seed_arxiv_ids: []   # e.g. ["2606.25340"]
  days: 7              # the arXiv leg only; S2 recommends within a fixed 60 days
  max_candidates: 40
  min_relevance:       # drop candidates below this score; empty = keep all
  # A third leg: keyword search over the whole Semantic Scholar corpus.
  # The other two can only ever see new papers — S2 recommends within 60
  # days and the arXiv leg reads a rolling listing — so this is the only
  # one that can find something published last year. Empty = off.
  bulk_queries: []     # e.g. ["fracton topological order"]
  bulk_years:          # e.g. "2023-"; empty = any year
  # Your own papers, for `magi radar citation-gap`. Left empty it falls
  # back to seed_arxiv_ids above — which are usually other people's, and
  # the report then asks who failed to cite them.
  own_arxiv_ids: []
"""
    safe_write(topic_path / "config.yaml", config_yaml, args.force)

    # 8. .gitignore. A topic workspace is a directory of markdown a researcher
    #    will very reasonably push somewhere, and nothing here said which parts
    #    of it are rebuildable and which are the only copy of a decision.
    #
    #    The two exclusions are the point. `output/` looks entirely generated
    #    and mostly is, but `output/ingest/` records what was queued, converted
    #    and approved, and `output/radar/` records which candidates a person
    #    said no to — re-running rebuilds neither, because the upstream windows
    #    have moved on. A blanket `output/` would quietly drop both.
    gitignore = """# What `magi` will make again. Everything else here is yours.

scratch/
output/*.db
output/*.db-wal
output/*.db-shm
output/.lint_cache.json
output/.embeddings_cache*

# Deliberately NOT ignored, and not an oversight:
#   output/ingest/   what was queued, converted, decided and committed
#   output/radar/    which candidates you already said no to
# Neither can be regenerated — a re-run returns a different world — so they
# are tracked alongside the library they describe.

# Ingest leaves the originals here until they are filed.
inbox/.processed/

# Backups taken before a pass that rewrites cards in place.
**/.backup/

.DS_Store
Thumbs.db
"""
    safe_write(topic_path / ".gitignore", gitignore, args.force)

    print(f"Workspace initialized successfully at: {topic_path}")

    # Put it in the global registry now rather than as a side effect of the
    # first `magi index`. Until that ran, a freshly created workspace was
    # absent from /api/kb — so it did not appear in the WebUI's workspace
    # picker or to the browser extension, and the two surfaces that exist to
    # get material *into* a new library were the two that could not see it.
    # register_kb is idempotent on the resolved path, and takes no name so it
    # picks the same one `magi index` would.
    try:
        from magi.kb_registry import register_kb

        register_kb(topic_path, quiet=True)
        print(f"Registered as a knowledge base — it will show up in 'magi kb list' "
              f"and the WebUI workspace picker.")
    except Exception as exc:  # non-fatal: the workspace itself is scaffolded
        print(f"Warning: could not register this workspace: {exc}")

    print("Next: cd into it, then 'magi skills install' to give your agent CLI "
          "this workspace's skills, and 'magi sync' to see what to do first.")

    # 8. Auto-register in an ancestor hub when the topic sits under <hub>/topics/.
    try:
        import subprocess
        from magi.core.workspace import find_hub_root
        hub = find_hub_root(topic_path.parent)
        if hub is not None and topic_path.parent == (hub / "topics").resolve():
            slug = topic_path.name
            result = subprocess.run(
                [sys.executable, "-m", "magi", "hub", "register", slug, "--hub", str(hub)],
                capture_output=True, text=True,
            )
            if result.returncode == 0:
                print(f"Registered topic '{slug}' in hub registry at {hub}")
            else:
                detail = (result.stderr or result.stdout).strip()
                print(f"Warning: could not auto-register topic in hub {hub}: {detail}")
    except Exception as exc:  # non-fatal: workspace itself is already scaffolded
        print(f"Warning: hub auto-registration skipped: {exc}")

if __name__ == "__main__":
    sys.exit(main())
