#!/usr/bin/env python
"""Programmatically initialize topic workspace folders and default templates.
"""

import os
import sys
import argparse
from datetime import date
from pathlib import Path

def safe_write(p: Path, content: str, force: bool):
    if p.exists() and not force:
        print(f"Skipping existing {p}")
        return
    p.write_text(content, encoding="utf-8")

def create_minimal_index(path: Path, title: str, today: str, force: bool = False):
    content = (
        f"# {title} Index\n\n"
        f"> Generated by local magi lint.\n\n"
        f"Last updated: {today}\n\n"
        f"## Contents\n\n"
        f"| File | Summary | Tags | Updated |\n"
        f"|------|---------|------|---------|\n\n"
        f"## Recent Changes\n\n"
        f"- {today}: Created missing index.\n"
    )
    safe_write(path, content, force)

def main(argv=None):
    parser = argparse.ArgumentParser(prog="magi init", description="Initialize topic workspace")
    parser.add_argument("--topic-dir", default=".", help="Topic directory path (default: current directory)")
    parser.add_argument("--name", default="My Topic", help="Topic name/title")
    parser.add_argument("--scope", default="A topic wiki.", help="Topic scope description")
    parser.add_argument("--force", action="store_true", help="Overwrite existing config/log/index files")
    args = parser.parse_args(argv)

    topic_path = Path(args.topic_dir).resolve()
    today = date.today().isoformat()

    # 1. Folders to create
    subdirs = [
        "raw",
        "raw/articles",
        "raw/papers",
        "raw/repos",
        "raw/notes",
        "raw/data",
        "wiki",
        "wiki/concepts",
        "wiki/topics",
        "wiki/references",
        "wiki/theses",
        "output",
        "inbox",
        "inbox/.processed",
        "scratch"
    ]

    for d in subdirs:
        p = topic_path / d
        p.mkdir(parents=True, exist_ok=True)

    # 2. config.md
    config_content = f"""---
title: "{args.name}"
scope: "{args.scope}"
created: {today}
---

# {args.name}

## Scope

{args.scope}

## Conventions

- Source files go in `raw/` under the appropriate subdirectory
- Compiled articles go in `wiki/references/` (papers) and `wiki/concepts/` (terms)
- All compiled pages use YAML frontmatter and `[[double-bracket]]` concept links
"""
    safe_write(topic_path / "config.md", config_content, args.force)

    # 3. log.md
    log_content = f"""# Log

## [{today}] init | Created new topic wiki
"""
    safe_write(topic_path / "log.md", log_content, args.force)

    # 4. Root _index.md
    root_index_content = f"""# {args.name}

> Topic wiki initialized on {today}.

## Quick Navigation

| Directory | Purpose |
|-----------|---------|
| [raw/](raw/) | Raw source materials |
| [wiki/](wiki/) | Compiled knowledge base |
| [output/](output/) | Generated artifacts |
| [inbox/](inbox/) | Pending ingestion |

## Statistics

- Raw sources: 0
- Compiled articles: 0
- Concepts: 0
"""
    safe_write(topic_path / "_index.md", root_index_content, args.force)

    # 5. Minimal _index.md files for subdirectories
    dir_titles = [
        ("raw", "Raw"),
        ("raw/articles", "Articles"),
        ("raw/papers", "Papers"),
        ("raw/repos", "Repos"),
        ("raw/notes", "Notes"),
        ("raw/data", "Data"),
        ("wiki", "Wiki"),
        ("wiki/concepts", "Concepts"),
        ("wiki/topics", "Topics"),
        ("wiki/references", "References"),
        ("wiki/theses", "Theses"),
        ("output", "Output"),
    ]

    for rel_path, title in dir_titles:
        p = topic_path / rel_path / "_index.md"
        create_minimal_index(p, title, today, args.force)

    # 6. Agent entry protocol: CLAUDE.md (Claude Code) + AGENTS.md (Codex
    # et al.) share one body so every host gets the same onboarding.
    protocol = f"""# MAGI Research Workspace: {args.name}

This directory is a MAGI topic workspace — an agent-native research
environment. Scope: {args.scope}

## On entering (do this first)

1. `magi sync` — sync ratio, three-core status, and concrete restore hints.
   Add `--fix` to run the deterministic ones (graph build, index, backlog
   sync, task store) instead of typing them out; it reports what still
   needs a person. `--dry-run` shows the plan first.
2. `bd prime` — inject current work state (ready/blocked/in-progress tasks).

## The three cores

- **Knowledge** (`wiki/`): concept cards, reference cards, theses.
  Produced by the ingest/compile skills; queried via `magi graph query`,
  `magi wiki context`, `magi grep`.
- **Work state** (beads): `bd ready` lists actionable tasks. Track research
  work with typed issues: question / survey / derivation / computation /
  experiment / review (`bd create -t <type> "..."`). These six research types
  are CUSTOM types configured by `magi pm init`; the generic type list from
  `bd prime` (task/bug/feature) does not supersede them.
- **Retrieval**: `magi search "..."` (hybrid BM25+vector; build/refresh with
  `magi index`); `magi grep` for exact regex. After a search, always read the
  underlying file before citing it.

## Shortcuts worth preferring

- `magi sync --fix` instead of running graph/index/backlog commands by hand.
- `magi ingest auto <path>` (or bare, for all of `inbox/`) instead of choosing
  between ingest mineru/ocr/tex/add and remembering `ingest finalize`.
- `magi each <command>` to run one command across every topic of a hub.

## Ground rules

- Durable state lives in files and databases here — not in your context.
  Record work in bd issues; record knowledge as wiki cards.
- Do NOT answer research questions from parametric memory. Retrieve from
  `wiki/` and cite `[[wikilinks]]`; verify claims with `magi verify`.
- Syntax for any command: `magi <command> --help`. Overview: `magi --help`.
- Stuck, or asked how something works? The manual ships with the CLI —
  `magi guide --search "<the error>"` finds the section, `magi guide
  --symptoms` is the symptom→fix index, `magi guide <chapter>` reads one.
  Prefer it over recalling flags from memory; add `--json` for parsing.
- The wiki_* skills teach when/why to run each pipeline (ingest, compile,
  enrich, link, lint, ask, audit, research).
"""
    safe_write(topic_path / "CLAUDE.md", protocol, args.force)
    safe_write(topic_path / "AGENTS.md", protocol, args.force)

    # 7. Starter config.yaml (workspace-level; wins over ~/.config/magi/)
    config_yaml = """# MAGI workspace configuration (discovered by upward walk from cwd)
ollama:
  base_url: "http://127.0.0.1:11434"
models:
  ocr: "glm-ocr"
  embedding: "qwen3-embedding:0.6b"
ocr:
  mineru_api_token: ""
  use_mineru: false
  timeout: 180
  dpi: 130
semantic_link:
  threshold: 0.75
  merge_threshold: 0.85
  auto_merge_threshold: 0.95

# Literature radar (magi radar harvest)
radar:
  arxiv_categories:
    - cond-mat.str-el
    - hep-th
  seed_arxiv_ids: []   # e.g. ["2606.25340"]; library arXiv IDs auto-merge in
  days: 7
  max_candidates: 40
"""
    safe_write(topic_path / "config.yaml", config_yaml, args.force)

    print(f"Workspace initialized successfully at: {topic_path}")
    print("Next: cd into it, then 'magi skills install' to give your agent CLI "
          "this workspace's skills, and 'magi sync' to see what to do first.")

    # 8. Auto-register in an ancestor hub when the topic sits under <hub>/topics/.
    try:
        import subprocess
        from magi.core.workspace import find_hub_root
        hub = find_hub_root(topic_path.parent)
        if hub is not None and topic_path.parent == (hub / "topics").resolve():
            slug = topic_path.name
            result = subprocess.run(
                [sys.executable, "-m", "magi", "hub", "register", slug, "--hub", str(hub)],
                capture_output=True, text=True,
            )
            if result.returncode == 0:
                print(f"Registered topic '{slug}' in hub registry at {hub}")
            else:
                detail = (result.stderr or result.stdout).strip()
                print(f"Warning: could not auto-register topic in hub {hub}: {detail}")
    except Exception as exc:  # non-fatal: workspace itself is already scaffolded
        print(f"Warning: hub auto-registration skipped: {exc}")

if __name__ == "__main__":
    sys.exit(main())
