"""One `_index.md`, one format, whichever command touched it last.

Four functions rendered these files in three different formats, and three
orchestrators ran them in three different orders:

    magi ingest finalize   lint --fix -> graph build -> wiki reindex
    wiki_compile skill     wiki reindex -> lint --fix
    magi init              its own hand-rolled shell

So ingesting a paper, compiling it, and ingesting another rewrote
`wiki/concepts/_index.md` three different ways — each rewrite a whole-file
diff, and each one bumping the wiki's mtime and pushing the graph to "stale".
`magi sync` had a special case excluding `_index.md` from its freshness scan
to paper over exactly this.

These tests fix the format by fixing the *fixed point*: run the writers in any
order and the file stops changing.
"""

import subprocess
import sys

import pytest

from magi.core.wiki_common import render_index, write_index


CARDS = {
    "toric-code.md": "---\ntitle: Toric Code\n"
                     "summary: A stabilizer code with | a pipe in it\n"
                     "tags: [topology, qec]\ncategory: Models\n"
                     "updated: 2026-08-01\n---\nBody.\n",
    "anyons.md": "---\ntitle: Anyons\nsummary: Exotic statistics\n"
                 "tags: [topology]\ncategory: Phenomena\n"
                 "ingested: 2026-08-02\n---\nBody.\n",
}


@pytest.fixture
def workspace(tmp_path):
    subprocess.run([sys.executable, "-m", "magi", "init",
                    "--topic-dir", str(tmp_path), "--name", "T"],
                   capture_output=True, text=True, check=True)
    for name, body in CARDS.items():
        (tmp_path / "wiki" / "concepts" / name).write_text(body, encoding="utf-8")
    # Settle the cards first. `lint --fix` fills in frontmatter a card is
    # missing — a card with `ingested` but no `updated` gains one — so a
    # convergence test run against unsettled cards compares two states that
    # legitimately differ, and blames the renderer for it.
    _magi(tmp_path, "lint", "--fix", ".")
    return tmp_path


def _magi(ws, *args):
    """Run a magi subcommand. `lint` exits non-zero when it *finds* something,
    which is not the same as failing, so only a crash is an error here."""
    res = subprocess.run([sys.executable, "-m", "magi", *args], cwd=ws,
                         capture_output=True, text=True, encoding="utf-8",
                         errors="replace")
    assert "Traceback" not in res.stderr, res.stderr
    return res


def _index(ws):
    return (ws / "wiki" / "concepts" / "_index.md").read_text(encoding="utf-8")


# --------------------------------------------------------------------------
# the fixed point
# --------------------------------------------------------------------------

def test_the_two_orchestrator_orders_agree(workspace):
    """`ingest finalize` ends on reindex, `wiki_compile` ends on lint. Whoever
    went last used to decide the format."""
    _magi(workspace, "wiki", "reindex", ".")
    _magi(workspace, "lint", "--fix", ".")
    after_finalize_order = _index(workspace)

    _magi(workspace, "lint", "--fix", ".")
    _magi(workspace, "wiki", "reindex", ".")
    after_compile_order = _index(workspace)

    assert after_finalize_order == after_compile_order


def test_a_rebuild_after_a_new_file_still_lands_on_the_same_format(workspace):
    """lint only regenerates when it notices a file missing from the table, so
    this is the path that actually fired in the wild."""
    _magi(workspace, "wiki", "reindex", ".")
    (workspace / "wiki" / "concepts" / "fracton.md").write_text(
        "---\ntitle: Fracton\nsummary: Restricted mobility\ntags: [topology]\n"
        "category: Models\ncreated: 2026-08-03\n---\nBody.\n", encoding="utf-8")

    _magi(workspace, "lint", "--fix", ".")
    by_lint = _index(workspace)
    _magi(workspace, "wiki", "reindex", ".")
    assert _index(workspace) == by_lint
    _magi(workspace, "lint", "--fix", ".")
    assert _index(workspace) == by_lint


def test_init_writes_the_same_shape_as_everything_else(tmp_path):
    """The scaffolded index claimed "Generated by local magi lint", which was
    never true of `magi init`."""
    subprocess.run([sys.executable, "-m", "magi", "init",
                    "--topic-dir", str(tmp_path), "--name", "T"],
                   capture_output=True, text=True, check=True)
    scaffolded = _index(tmp_path)

    _magi(tmp_path, "wiki", "reindex", ".")
    assert _index(tmp_path) == scaffolded


# --------------------------------------------------------------------------
# what a rebuild must not destroy, and must not churn
# --------------------------------------------------------------------------

def test_a_hand_written_changelog_survives_a_rebuild(workspace):
    """Nothing generates `## Recent Changes`; the template invites an agent to
    keep one there. A rebuild that ate it would be this same bug again."""
    _magi(workspace, "wiki", "reindex", ".")
    path = workspace / "wiki" / "concepts" / "_index.md"
    path.write_text(path.read_text(encoding="utf-8")
                    + "\n## Recent Changes\n\n*   **2026-08-05**: kept\n",
                    encoding="utf-8")

    _magi(workspace, "wiki", "reindex", ".")
    _magi(workspace, "lint", "--fix", ".")

    assert "2026-08-05" in _index(workspace)


def test_an_unchanged_index_is_not_restamped(workspace):
    """`Last updated` is part of the content, so writing it unconditionally
    made every index in the wiki dirty once a day whether or not a row had
    moved — and a wiki mtime that pushes the graph to "stale" for nothing."""
    _magi(workspace, "wiki", "reindex", ".")
    path = workspace / "wiki" / "concepts" / "_index.md"
    # Only the stamp line — the same date sits in the table rows, and moving
    # those would be a real change that *should* be rewritten.
    path.write_text("\n".join(
        "Last updated: 2020-01-01" if line.startswith("Last updated:") else line
        for line in path.read_text(encoding="utf-8").split("\n")), encoding="utf-8")

    _magi(workspace, "wiki", "reindex", ".")

    assert "Last updated: 2020-01-01" in _index(workspace), (
        "an index whose rows did not move was rewritten anyway")


def test_a_real_change_does_restamp(workspace):
    _magi(workspace, "wiki", "reindex", ".")
    (workspace / "wiki" / "concepts" / "new.md").write_text(
        "---\ntitle: New\nsummary: s\n---\nB.\n", encoding="utf-8")

    _magi(workspace, "wiki", "reindex", ".")

    assert "new.md" in _index(workspace)


# --------------------------------------------------------------------------
# the cell-level disagreements
# --------------------------------------------------------------------------

def test_a_pipe_in_a_summary_does_not_tear_the_table(workspace):
    """Only one of the old renderers escaped pipes."""
    _magi(workspace, "wiki", "reindex", ".")
    row = [l for l in _index(workspace).split("\n") if "toric-code.md" in l][0]
    assert r"\|" in row
    assert row.count("|") - row.count(r"\|") == 5


@pytest.mark.parametrize("key", ["updated", "ingested", "created"])
def test_every_dating_convention_is_honoured(tmp_path, key):
    """Ingest routes stamp `ingested`, templates stamp `created`, edits stamp
    `updated`. One renderer read only two of the three, so how a card was
    dated in the table depended on how it had arrived."""
    d = tmp_path / "concepts"
    d.mkdir()
    (d / "a.md").write_text(f"---\ntitle: A\n{key}: 2026-08-01\n---\nx\n",
                            encoding="utf-8")

    assert "2026-08-01" in render_index(d, today="2026-08-26")


def test_categories_appear_only_when_they_separate_something(tmp_path):
    """A Categories list that puts every file under "Uncategorized" is the
    Contents table again wearing a hat."""
    d = tmp_path / "concepts"
    d.mkdir()
    (d / "a.md").write_text("---\ntitle: A\n---\nx\n", encoding="utf-8")
    assert "## Categories" not in render_index(d, today="2026-08-26")

    (d / "b.md").write_text("---\ntitle: B\ncategory: Models\n---\nx\n",
                            encoding="utf-8")
    assert "## Categories" in render_index(d, today="2026-08-26")


def test_reindex_covers_every_wiki_directory_init_creates(workspace):
    """`magi init` scaffolds four; reindex maintained two, so `topics/` and
    `theses/` drifted to whatever lint happened to do to them."""
    _magi(workspace, "wiki", "reindex", ".")
    for name in ("references", "concepts", "topics", "theses"):
        assert (workspace / "wiki" / name / "_index.md").is_file(), name


def test_the_write_is_atomic(tmp_path):
    """`wiki/` is ORIGINAL and the WebUI cancels jobs with `taskkill /F /T`,
    so a half-written index is a real outcome."""
    d = tmp_path / "concepts"
    d.mkdir()
    (d / "a.md").write_text("---\ntitle: A\n---\nx\n", encoding="utf-8")

    assert write_index(d / "_index.md", today="2026-08-26") is True
    assert not list(d.glob(".tmp_atomic_*")), "temp file left behind"
    assert write_index(d / "_index.md", today="2026-08-26") is False
