#!/usr/bin/env python
"""Programmatically initialize topic workspace folders and default templates.
"""

import os
import shutil
import sys
import argparse
from datetime import date, datetime
from pathlib import Path

from magi.core import managed

def keep_a_copy(p: Path) -> Path:
    """Put the current contents of *p* somewhere recoverable, and say where.

    `.backup` is the convention the rest of the workspace already uses — every
    scanner skips a path with it as a component, and `magi wiki
    refactor-concept` and `magi link` both write there. A second-granularity
    stamp is not a unique name, so take the first free one rather than
    overwriting the copy an earlier call in this same run just made.
    """
    stamp = datetime.now().strftime("%Y-%m-%d_%H%M%S")
    backup_dir = p.parent / ".backup"
    backup_dir.mkdir(parents=True, exist_ok=True)
    dest = backup_dir / f"{p.stem}_{stamp}{p.suffix}"
    n = 2
    while dest.exists():
        dest = backup_dir / f"{p.stem}_{stamp}-{n}{p.suffix}"
        n += 1
    shutil.copy2(p, dest)
    return dest

DECISIONS_STARTER = """# Decisions

Only what a person decided, and why in their own words. An agent transcribes
here; nothing writes to this file on its own initiative. A decision that is not
in this file was not made — it was assumed.
"""

NOTES_STARTER = """# Notes

Anything, in any order, whenever it occurs to you. Append; do not tidy. The
next `magi next` files each line where it belongs — a question, a proposition,
a decision, a post on an existing note, or a task — and leaves a link back.
"""

CLAUDE_POINTER = "@AGENTS.md\n"


def safe_write(p: Path, content: str, force: bool):
    if p.exists():
        if not force:
            print(f"Skipping existing {p}")
            return
        # --force is the only way to reach this line, and what it lands on is
        # ORIGINAL: config.md is the scope a person wrote, log.md is the
        # running record, config.yaml is their settings. "Overwrite existing
        # config/log/index files" is an honest description of the flag and
        # still leaves no way back from a mistyped one.
        kept = keep_a_copy(p)
        print(f"Overwriting {p} (previous contents kept at {kept})")
    p.write_text(content, encoding="utf-8")

def create_minimal_index(path: Path, title: str, today: str, force: bool = False):
    """Scaffold one directory's `_index.md` using the shared renderer.

    The hand-rolled version here claimed "Generated by local magi lint",
    which was never true of this command, and emitted a `## Recent Changes`
    section with one bootstrap line that nothing ever added to. Between them,
    `magi init`, `magi lint --fix` and `magi wiki reindex` wrote three
    different formats into the same file.
    """
    from magi.core.wiki_common import render_index

    safe_write(path, render_index(path.parent, today=today), force)

def main(argv=None):
    parser = argparse.ArgumentParser(prog="magi init", description="Initialize topic workspace")
    parser.add_argument("--topic-dir", default=".", help="Topic directory path (default: current directory)")
    parser.add_argument("--name", default="My Topic", help="Topic name/title")
    parser.add_argument("--scope", default="A topic wiki.", help="Topic scope description")
    parser.add_argument("--coaching", default="light",
                        choices=["off", "light", "strict"],
                        help="How hard the workspace asks its human for a prediction. "
                             "strict refuses to start a derivation without one.")
    parser.add_argument("--force", action="store_true", help="Overwrite existing config/log/index files")
    args = parser.parse_args(argv)

    topic_path = Path(args.topic_dir).resolve()
    today = date.today().isoformat()

    # 1. Folders to create
    subdirs = [
        "raw",
        "raw/articles",
        "raw/papers",
        "raw/repos",
        "raw/notes",
        "raw/data",
        "wiki",
        "wiki/concepts",
        "wiki/topics",
        "wiki/references",
        # v2: research state lives in files, not in a task tracker. `threads/`
        # holds propositions, questions and lines; `drafts/` holds the working
        # out they point at. `wiki/theses/` is retired into the two of them —
        # existing workspaces keep theirs until `magi migrate` moves it.
        "threads",
        "drafts",
        "output",
        "inbox",
        "inbox/.processed",
        "scratch"
    ]

    for d in subdirs:
        p = topic_path / d
        p.mkdir(parents=True, exist_ok=True)

    # 2. config.md
    config_content = f"""---
title: "{args.name}"
scope: "{args.scope}"
created: {today}
---

# {args.name}

## Scope

{args.scope}

## Conventions

- Source files go in `raw/` under the appropriate subdirectory
- Compiled articles go in `wiki/references/` (papers) and `wiki/concepts/` (terms)
- All compiled pages use YAML frontmatter and `[[double-bracket]]` concept links
"""
    safe_write(topic_path / "config.md", config_content, args.force)

    # 3. No log.md. The record is the posts in `threads/`, read with `magi
    #    feed`. A workspace that already has one keeps it — nothing writes to
    #    it any more, and nothing reads it either.

    # 4. Root _index.md
    root_index_content = f"""# {args.name}

> Topic wiki initialized on {today}.

## Quick Navigation

| Directory | Purpose |
|-----------|---------|
| [raw/](raw/) | Raw source materials |
| [wiki/](wiki/) | Compiled knowledge base |
| [output/](output/) | Generated artifacts — except `output/ingest/`, `output/radar/`, `output/reflect/` and `output/llm-ledger.jsonl`, which record decisions you made or what they cost, and cannot be rebuilt |
| [inbox/](inbox/) | Pending ingestion |

## Statistics

- Raw sources: 0
- Compiled articles: 0
- Concepts: 0
"""
    safe_write(topic_path / "_index.md", root_index_content, args.force)

    # 5. Minimal _index.md files for subdirectories
    dir_titles = [
        ("raw", "Raw"),
        ("raw/articles", "Articles"),
        ("raw/papers", "Papers"),
        ("raw/repos", "Repos"),
        ("raw/notes", "Notes"),
        ("raw/data", "Data"),
        ("wiki", "Wiki"),
        ("wiki/concepts", "Concepts"),
        ("wiki/topics", "Topics"),
        ("wiki/references", "References"),
        ("output", "Output"),
    ]

    for rel_path, title in dir_titles:
        p = topic_path / rel_path / "_index.md"
        create_minimal_index(p, title, today, args.force)

    # 5b. The human's two surfaces. `decisions.md` is the only file MAGI
    # never writes on its own initiative — an agent transcribes what a person
    # decided and nothing else. `inbox/notes.md` is the opposite: anything,
    # unsorted, and `magi next` files it.
    safe_write(topic_path / "decisions.md", DECISIONS_STARTER, args.force)
    safe_write(topic_path / "inbox" / "notes.md", NOTES_STARTER, args.force)

    # 6. Agent entry protocol: CLAUDE.md (Claude Code) + AGENTS.md (Codex
    # et al.) share one body so every host gets the same onboarding.
    # The protocol is one text, in `core/managed.py`, because it is read at
    # the start of every session on every host — and because `magi install`
    # has to be able to rewrite it in place when it changes.
    protocol = managed.body(args.name, args.scope, args.coaching)
    # The protocol goes in a marked block so upgrades can rewrite it without
    # touching what a person added around it. CLAUDE.md holds one line so
    # there is a single text to keep current, not two that drift.
    managed.write(topic_path / "AGENTS.md", protocol)
    safe_write(topic_path / "CLAUDE.md", CLAUDE_POINTER, args.force)

    # 7. Starter config.yaml (workspace-level; wins over ~/.config/magi/)
    # `research:` is written out even at the default, so the level the gate
    # reads is visible in the file rather than implied by its absence — and so
    # `--coaching strict` means the same thing to the gate as it does to the
    # protocol text the agent was just handed.
    config_yaml = """# MAGI workspace configuration (discovered by upward walk from cwd)
research:
  coaching: light      # off | light | strict — how hard the close gate pushes
  wip_limit: 3         # open propositions per line before it asks a person
  stall_days: 14       # days of silence before a line is called quiet
  review_host:         # empty = probe PATH for a CLI that is not the author
  review_model:        # empty = that host's cheap tier (haiku, flash-low, …)
                       # one string for every vendor: pin review_host too, or
                       # put `model:` on a research.hosts record instead
  review_effort:       # low | medium | high; empty = that host's own default
  weekly_calls: 40     # MAGI's own model calls per week; failed ones count
  llm_calls: true      # master switch for MAGI's own calls
  rule_budget: 7       # lines the AGENTS.md rule section may hold
  rules: []            # rules this library earned; `magi reflect promote` adds them
  hosts: []            # agent CLIs beyond the built-in ones; `magi skills where` lists all
ollama:
  base_url: "http://127.0.0.1:11434"
  autostart: true      # start a stopped local Ollama on demand
  embed_batch: 16      # chunks per embedding request; raise on a roomy machine
models:
  ocr: "glm-ocr:q8_0"
  embedding: "qwen3-embedding:0.6b"
ocr:
  # Deliberately absent, not empty. Settings layer: this file overrides
  # ~/.config/magi/config.yaml key by key, and an explicit "" is a value —
  # it would shadow a token set once for you and leave every new workspace
  # unable to reach MinerU for no visible reason. Put the token in the user
  # file; uncomment here only to give this one topic a different key.
  # mineru_api_token: ""
  use_mineru: false
  timeout: 180
  dpi: 150
semantic_link:
  threshold: 0.75
  merge_threshold: 0.85
  auto_merge_threshold: 0.95

# Literature radar (magi radar harvest)
radar:
  # A Semantic Scholar key is free and optional; without one the radar
  # shares an anonymous quota with everybody. $SEMANTIC_SCHOLAR_API_KEY
  # wins over this file. Deliberately absent rather than empty — see the
  # note on ocr.mineru_api_token above for why.
  # s2_api_key: ""
  arxiv_categories:
    - cond-mat.str-el
    - hep-th
  # Papers that describe what you care about — often other people's. May stay
  # empty: every arXiv ID on a reference card is merged in automatically.
  seed_arxiv_ids: []   # e.g. ["2606.25340"]
  days: 7              # the arXiv leg only; S2 recommends within a fixed 60 days
  max_candidates: 40
  min_relevance:       # drop candidates below this score; empty = keep all
  # A third leg: keyword search over the whole Semantic Scholar corpus.
  # The other two can only ever see new papers — S2 recommends within 60
  # days and the arXiv leg reads a rolling listing — so this is the only
  # one that can find something published last year. Empty = off.
  bulk_queries: []     # e.g. ["fracton topological order"]
  bulk_years:          # e.g. "2023-"; empty = any year
  # Your own papers, for `magi radar citation-gap`. Left empty it falls
  # back to seed_arxiv_ids above — which are usually other people's, and
  # the report then asks who failed to cite them.
  own_arxiv_ids: []
"""
    if args.coaching != "light":
        config_yaml = config_yaml.replace("coaching: light",
                                          f"coaching: {args.coaching}", 1)
    safe_write(topic_path / "config.yaml", config_yaml, args.force)

    # 8. .gitignore. A topic workspace is a directory of markdown a researcher
    #    will very reasonably push somewhere, and nothing here said which parts
    #    of it are rebuildable and which are the only copy of a decision.
    #
    #    The two exclusions are the point. `output/` looks entirely generated
    #    and mostly is, but `output/ingest/` records what was queued, converted
    #    and approved, `output/radar/` records which candidates a person said
    #    no to, and `output/reflect/` holds what the slow loop understood from
    #    transcripts that have since rotated away — re-running rebuilds none of
    #    them, because the upstream windows have moved on. A blanket `output/`
    #    would quietly drop all of it.
    gitignore = """# What `magi` will make again. Everything else here is yours.

scratch/
output/*.db
output/*.db-wal
output/*.db-shm
output/.lint_cache.json
output/.embeddings_cache*

# Deliberately NOT ignored, and not an oversight:
#   output/ingest/           what was queued, converted, decided and committed
#   output/radar/            which candidates you already said no to
#   output/reflect/          what the slow loop noticed, and what you did about it
#   output/llm-ledger.jsonl  what MAGI's own model calls cost you this week
# None of it can be regenerated — a re-run returns a different world, and the
# transcripts the slow loop read have rotated away — so they are tracked
# alongside the library they describe.

# Ingest leaves the originals here until they are filed.
inbox/.processed/

# Backups taken before a pass that rewrites cards in place.
**/.backup/

.DS_Store
Thumbs.db
"""
    safe_write(topic_path / ".gitignore", gitignore, args.force)

    print(f"Workspace initialized successfully at: {topic_path}")

    # Put it in the global registry now rather than as a side effect of the
    # first `magi index`. Until that ran, a freshly created workspace was
    # absent from /api/kb — so it did not appear in the WebUI's workspace
    # picker or to the browser extension, and the two surfaces that exist to
    # get material *into* a new library were the two that could not see it.
    # register_kb is idempotent on the resolved path, and takes no name so it
    # picks the same one `magi index` would.
    try:
        from magi.kb_registry import register_kb

        register_kb(topic_path, quiet=True)
        print(f"Registered as a knowledge base — it will show up in 'magi kb list' "
              f"and the WebUI workspace picker.")
    except Exception as exc:  # non-fatal: the workspace itself is scaffolded
        print(f"Warning: could not register this workspace: {exc}")

    # There is no step 8. A topic under `<hub>/topics/` used to be registered
    # in that hub as well, by shelling out to `magi hub register` — a command
    # retired in M3 along with hubs themselves, when a research line became a
    # view over one project rather than a directory in a tree. The call stayed
    # behind and printed "unknown command 'hub'" as a warning on every init in
    # such a directory, which is how a person learns to ignore warnings. What
    # still matters is `register_kb` above: it is what `magi kb list` and the
    # WebUI picker read, and it has already run.

    print("Next: cd into it, then 'magi skills install' to give your agent CLI "
          "this workspace's skills, and 'magi sync' to see what to do first.")

if __name__ == "__main__":
    sys.exit(main())
