"""arXiv's own LaTeXML-rendered HTML — the best source we can get for a paper.

Since December 2023 arXiv publishes an HTML rendering of most submissions,
generated by LaTeXML from the author's LaTeX. Every formula in it carries the
original TeX **twice**: once in the ``alttext`` attribute of the ``<math>``
element and once in ``<annotation encoding="application/x-tex">``. Measured on
a real 2026 hep-th paper: 767 ``<math>`` elements, 767 ``alttext``, 767
annotations — a perfect one-to-one-to-one.

That makes this route categorically different from every other one. It is not
recognition. Nothing is being read off a rendered page and guessed at; the TeX
was written down and we are reading it back. It also sidesteps three failure
modes of converting the e-print tarball ourselves, all three of which were
measured on real submissions:

  * picking the wrong main .tex out of a bundle that ships several
  * multi-file submissions stitched together with \\input
  * pandoc dying on old plain-TeX primitives (``\\vskip 0.3truein`` killed
    cond-mat/0001002 outright, producing nothing)

and it does not silently lose figures the way the tarball route can (arXiv
2401.00506: six referenced, zero survived, run reported success).

Coverage, measured: 8/10 recent papers on the native endpoint; 14/15 on ar5iv
for the pre-2023 range that dominates an older physics library. Papers that
miss on both are a real outcome, not an era artifact — fall through to the
tarball.
"""

from __future__ import annotations

import html as html_module
import os
import re
import subprocess
import tempfile
from datetime import datetime
from pathlib import Path
from urllib.error import HTTPError
from urllib.parse import urljoin

import yaml

from magi.core.arxiv_id import abs_url, normalize_arxiv_id
from magi.core.config_loader import load_config
from magi.core.http import http_get
from magi.core.tools import find_pandoc
from magi.core.wiki_common import atomic_write, slugify
from magi.ingest.convert_result import ConversionResult

NATIVE_URL = "https://arxiv.org/html/{id}"
AR5IV_URL = "https://ar5iv.labs.arxiv.org/html/{id}"

# arXiv answers a missing /html paper with its standard error page. Measured at
# exactly 7899 bytes; real renderings in the same sample ran 150 KB to 1.3 MB.
# The size alone is not the test — see _looks_like_a_paper — but it is a useful
# tripwire if that page ever grows.
_ERROR_PAGE_CEILING = 20_000

_MATH_ALTTEXT_RE = re.compile(r'<math[^>]*\balttext="([^"]*)"', re.IGNORECASE)
_ANNOTATION_RE = re.compile(
    r'<annotation encoding="application/x-tex">(.*?)</annotation>',
    re.IGNORECASE | re.DOTALL)
_TITLE_RE = re.compile(r"<title[^>]*>(.*?)</title>", re.IGNORECASE | re.DOTALL)


class FetchResult:
    """One attempt at one endpoint."""

    def __init__(self, ok: bool, *, body: bytes = b"", url: str = "",
                 endpoint: str = "", reason: str = ""):
        self.ok = ok
        self.body = body
        self.url = url
        self.endpoint = endpoint
        self.reason = reason


def _looks_like_a_paper(body: bytes, requested_url: str, final_url: str) -> tuple[bool, str]:
    """Did we actually get a rendering, or something that merely returned 200?

    Three ways this lies, all observed:

    * **ar5iv redirects to the abstract page** when it has no rendering. The
      status is 200 and the body is a real page — of the abstract. Scoring on
      the status code alone counts that as coverage.
    * **arXiv's /html 404 body** is a full HTML error page, not an empty one.
    * A rendering with no ``alttext`` anywhere is not useful to us even if it
      is a page about the right paper.
    """
    if "/abs/" in final_url and "/html/" in requested_url:
        return False, "redirected to the abstract page (no rendering exists)"
    if len(body) < _ERROR_PAGE_CEILING:
        return False, f"body is only {len(body)} bytes — an error page, not a paper"
    text = body.decode("utf-8", errors="replace")
    if not _MATH_ALTTEXT_RE.search(text) and "alttext=" not in text:
        return False, "rendering carries no alttext — the TeX is not recoverable from it"
    return True, ""


def fetch(arxiv_id: str, *, timeout: int = 60) -> FetchResult:
    """Native endpoint first, ar5iv second. Both are rate-limited to 15 s/request
    by the shared Throttle (arXiv's robots.txt sets Crawl-delay: 15 for /html)."""
    arxiv_id = normalize_arxiv_id(arxiv_id) or arxiv_id
    attempts = (("arxiv", NATIVE_URL.format(id=arxiv_id)),
                ("ar5iv", AR5IV_URL.format(id=arxiv_id)))
    last_reason = "no endpoint returned a rendering"
    for endpoint, url in attempts:
        try:
            body, _ctype, final_url = http_get(url, timeout=timeout)
        except HTTPError as exc:
            last_reason = f"{endpoint}: HTTP {exc.code}"
            continue
        except Exception as exc:  # noqa: BLE001 — urllib raises a family
            last_reason = f"{endpoint}: {exc}"
            continue
        ok, why = _looks_like_a_paper(body, url, final_url)
        if ok:
            return FetchResult(True, body=body, url=final_url, endpoint=endpoint)
        last_reason = f"{endpoint}: {why}"
    return FetchResult(False, reason=last_reason)


def extract_tex_formulas(page: str) -> list[str]:
    """Every formula's original TeX, in document order.

    Prefers ``<annotation>`` over ``alttext``: the attribute is HTML-escaped
    (``&lt;``, ``&amp;``) and the element is not, so the element needs no
    unescaping round-trip that could itself mangle a ``\\&`` or a ``<``.
    """
    annotations = _ANNOTATION_RE.findall(page)
    if annotations:
        return [html_module.unescape(a).strip() for a in annotations]
    return [html_module.unescape(a).strip() for a in _MATH_ALTTEXT_RE.findall(page)]


def page_title(page: str) -> str | None:
    m = _TITLE_RE.search(page)
    if not m:
        return None
    title = html_module.unescape(re.sub(r"\s+", " ", m.group(1))).strip()
    # arXiv prefixes the id: "[2608.20333] Real Title Here".
    return re.sub(r"^\[[^\]]+\]\s*", "", title) or None


def _rewrite_image_paths(md: str, arxiv_id: str) -> tuple[str, int, list[str]]:
    """Point figure references at ``images/`` and report the originals.

    arXiv serves figures as relative paths under ``{id}v{n}/``. Rewriting them
    to ``images/<name>`` matches what the tex and OCR routes already produce,
    which is what `ingest finalize` expects when it converts them to Obsidian
    wikilinks. The original relative targets come back so the caller can fetch
    them — rewriting without downloading would leave the wiki full of broken
    links, which is worse than the tarball route's silent drop, not better.
    """
    count = 0
    targets: list[str] = []
    # The page also carries arXiv's own chrome — funder logos, UI glyphs — as
    # absolute /static/... paths. Those are not this paper's figures; a real
    # figure is served relative to the page, under {id}v{n}/.
    figure_re = re.compile(rf"^{re.escape(arxiv_id)}v\d+/", re.IGNORECASE)

    def _is_ours(target: str) -> bool:
        if target.startswith(("http://", "https://", "data:", "images/", "/")):
            return False
        return bool(figure_re.match(target))

    def md_repl(m):
        nonlocal count
        target = m.group(2)
        if not _is_ours(target):
            return m.group(0)
        count += 1
        targets.append(target)
        return f"![{m.group(1)}](images/{os.path.basename(target)})"

    md = re.sub(r"!\[([^\]]*)\]\(([^)]+)\)", md_repl, md)

    # Pandoc leaves a figure it cannot express in Markdown as a raw <img>, which
    # is what happens to every real arXiv figure: they sit inside <figure>
    # elements carrying ids and classes. Handling only ![]() would silently miss
    # all of them — measured on 2608.20333, where both figures survived as HTML
    # and only arXiv's own smiley glyph came through as Markdown.
    def html_repl(m):
        nonlocal count
        target = m.group(2)
        if not _is_ours(target):
            return m.group(0)
        count += 1
        targets.append(target)
        return f'{m.group(1)}"images/{os.path.basename(target)}"'

    md = re.sub(r'(<(?:img|embed)\b[^>]*?\bsrc=)"([^"]+)"', html_repl, md,
                flags=re.IGNORECASE)
    return md, count, targets


def download_figures(targets, page_url: str, images_dir) -> tuple[int, list[str]]:
    """Fetch each relative figure next to the markdown. Returns (ok, failures).

    Throttled like any other arxiv.org request: the figures live under ``/html``
    too, and robots.txt sets ``Crawl-delay: 15`` for that whole path. That makes
    a five-figure paper cost about a minute, which is the honest price of not
    hammering someone else's server. Pass ``--no-figures`` when you would rather
    have the text now.
    """
    images_dir = Path(images_dir)
    ok = 0
    failures: list[str] = []
    seen: set[str] = set()
    for target in targets:
        name = os.path.basename(target)
        if not name or name in seen:
            continue
        seen.add(name)
        # Plain urljoin: the page URL ends in the paper id, which is a resource
        # not a directory, so `2608.20333v1/torus.png` resolves against /html/.
        # Appending a slash first would treat the id as a directory and produce
        # /html/2608.20333/2608.20333v1/torus.png.
        url = urljoin(page_url, target)
        try:
            body, _ctype, _final = http_get(url, timeout=60)
        except Exception as exc:  # noqa: BLE001
            failures.append(f"{name} ({exc})")
            continue
        images_dir.mkdir(parents=True, exist_ok=True)
        (images_dir / name).write_bytes(body)
        ok += 1
    return ok, failures


def _regroup_align_tables(md: str) -> tuple[str, int]:
    """Restore ``\\begin{aligned}`` around what LaTeXML split into table rows.

    LaTeXML wraps an ``align`` environment in a table with one ``<math>`` per
    row. Pandoc renders that as a grid table: the row order and the shared
    equation number survive, but the alignment is no longer expressed as LaTeX,
    so MathJax in Obsidian shows a table of separate equations instead of one
    aligned block. Measured on arXiv 2401.00506.

    Consecutive display-math blocks that carry ``&`` anchors are the signature
    of exactly this, so fold them back into one aligned environment.
    """
    block = re.compile(r"(?:^\$\$\n(.+?)\n\$\$\n?){2,}", re.MULTILINE | re.DOTALL)
    runs = 0

    def repl(m):
        nonlocal runs
        chunk = m.group(0)
        rows = re.findall(r"^\$\$\n(.+?)\n\$\$", chunk, re.MULTILINE | re.DOTALL)
        if len(rows) < 2 or not any("&" in r for r in rows):
            return chunk
        runs += 1
        body = " \\\\\n".join(r.strip() for r in rows)
        return "$$\n\\begin{aligned}\n" + body + "\n\\end{aligned}\n$$\n"

    return block.sub(repl, md), runs


def convert(arxiv_id: str, output_dir, *, doc_type: str | None = None,
            fetch_figures: bool = True) -> ConversionResult:
    """Fetch a paper's arXiv HTML and write it into ``output_dir`` as Markdown."""
    ident = normalize_arxiv_id(arxiv_id)
    if not ident:
        return ConversionResult.failed(f"'{arxiv_id}' is not an arXiv identifier.")

    output_dir = os.path.abspath(str(output_dir))
    os.makedirs(output_dir, exist_ok=True)

    print(f"Fetching arXiv HTML for {ident}...")
    got = fetch(ident)
    if not got.ok:
        print(f"No arXiv HTML rendering available: {got.reason}")
        return ConversionResult.failed(
            f"No arXiv HTML rendering for {ident}: {got.reason}")
    print(f"Got a rendering from {got.endpoint} ({len(got.body)} bytes)")

    page = got.body.decode("utf-8", errors="replace")
    formulas = extract_tex_formulas(page)
    title = page_title(page) or ident

    pandoc = find_pandoc()
    with tempfile.TemporaryDirectory() as tmp:
        src = os.path.join(tmp, "page.html")
        Path(src).write_bytes(got.body)
        out_md = os.path.join(tmp, "page.md")
        cmd = [pandoc, src, "-f", "html", "-t", "markdown", "-o", out_md]
        print(f"Running Pandoc: {' '.join(cmd)}")
        proc = subprocess.run(cmd, capture_output=True, text=True)
        if proc.returncode != 0:
            print("Pandoc conversion failed:")
            print(proc.stderr)
            return ConversionResult.failed(
                "Pandoc failed to convert the arXiv HTML.", proc.stderr.strip())
        md_content = Path(out_md).read_text(encoding="utf-8", errors="replace")

    md_content, n_figs, fig_targets = _rewrite_image_paths(md_content, ident)
    md_content, n_regrouped = _regroup_align_tables(md_content)

    images_dir = os.path.join(output_dir, "images")
    n_figs_ok, fig_failures = 0, []
    if fetch_figures and fig_targets:
        print(f"Fetching {len(set(os.path.basename(t) for t in fig_targets))} figure(s)...")
        n_figs_ok, fig_failures = download_figures(fig_targets, got.url, images_dir)
        print(f"Figures: {n_figs_ok} saved into images/, {len(fig_failures)} failed")

    if doc_type not in ("papers", "articles", "notes", "repos"):
        doc_type = os.path.basename(os.path.normpath(output_dir))
        if doc_type not in ("papers", "articles", "notes", "repos"):
            doc_type = "papers"

    today = datetime.now().strftime("%Y-%m-%d")
    fm = {
        "title": title,
        "source": got.url,
        "type": doc_type,
        "ingested": today,
        "tags": [],
        "summary": f"Converted from arXiv HTML ({got.endpoint}, LaTeXML).",
        "arxiv_id": ident,
        "arxiv_url": abs_url(ident),
    }
    frontmatter = ("---\n" + yaml.safe_dump(fm, allow_unicode=True, sort_keys=False,
                                            default_flow_style=False) + "---\n")

    output_path = os.path.join(output_dir, f"{today}-{slugify(title)}.md")
    atomic_write(output_path, frontmatter + "\n" + md_content, encoding="utf-8")
    print(f"Successfully converted and saved to {output_path}")

    outcome = ConversionResult(
        success=True,
        markdown_path=str(output_path),
        images_dir=images_dir,
    )
    outcome.flag("route-arxiv-html",
                 f"{len(formulas)} formula(s) carried verbatim TeX from {got.endpoint}",
                 severity="info")
    if n_regrouped:
        outcome.flag("align-regrouped",
                     f"{n_regrouped} multi-line equation group(s) restored to "
                     "\\begin{aligned}; LaTeXML had split them into table rows",
                     severity="info")
    if fig_failures:
        outcome.flag("figure-download-failed",
                     f"{len(fig_failures)} figure(s) could not be fetched and will "
                     f"be broken links: {', '.join(fig_failures[:5])}")
    elif n_figs and not fetch_figures:
        outcome.flag("figures-skipped",
                     f"{n_figs} figure reference(s) point at images/ but figure "
                     "fetching was disabled — these are broken links")
    elif n_figs_ok:
        outcome.flag("figures-saved", f"{n_figs_ok} figure(s) saved into images/",
                     severity="info")
    return outcome


def main(argv=None):
    import argparse

    parser = argparse.ArgumentParser(
        prog="magi ingest arxiv-html",
        description="Fetch arXiv's LaTeXML HTML for a paper and convert it to Markdown.")
    parser.add_argument("arxiv_id", help="arXiv identifier, e.g. 2608.16520 or cond-mat/0506438")
    parser.add_argument("-o", "--output_dir", required=True,
                        help="Output directory for the raw Markdown file.")
    parser.add_argument("--no-figures", action="store_true",
                        help="Skip figure downloads. Faster, but the figure links "
                             "in the output will be broken (arXiv asks for 15s "
                             "between requests, so figures dominate the wall time).")
    args = parser.parse_args(argv)

    result = convert(args.arxiv_id, args.output_dir,
                     fetch_figures=not args.no_figures)
    for finding in result.findings:
        print(f"  {finding}")
    return 0 if result.success else 1


if __name__ == "__main__":
    import sys
    sys.exit(main())
